DROP TABLE IF EXISTS NBA.DIM_SEASON;

CREATE TABLE NBA.DIM_SEASON AS
SELECT DISTINCT
	SEASON_2 AS SEASON,
	SEASON_1
FROM
	NBA.FCT_SHOT
WHERE
	SEASON_2 IS NOT NULL;

CREATE INDEX IF NOT EXISTS IX_DIM_SEASON ON NBA.DIM_SEASON (SEASON);