DROP TABLE IF EXISTS NBA.DIM_GAME;

CREATE TABLE NBA.DIM_GAME AS
SELECT DISTINCT
	GAME_ID,
	GAME_DATE,
	SEASON_2 AS SEASON,
	HOME_TEAM,
	AWAY_TEAM
FROM
	NBA.FCT_SHOT
WHERE
	GAME_ID IS NOT NULL;

CREATE INDEX IF NOT EXISTS IX_DIM_GAME_ID ON NBA.DIM_GAME (GAME_ID);

CREATE INDEX IF NOT EXISTS IX_DIM_GAME_SEASON ON NBA.DIM_GAME (SEASON);