CREATE INDEX IF NOT EXISTS IX_FCT_PLAYER ON NBA.FCT_SHOT (PLAYER_ID);

CREATE INDEX IF NOT EXISTS IX_FCT_TEAM ON NBA.FCT_SHOT (TEAM_ID);

CREATE INDEX IF NOT EXISTS IX_FCT_GAME ON NBA.FCT_SHOT (GAME_ID);

CREATE INDEX IF NOT EXISTS IX_FCT_SEASON ON NBA.FCT_SHOT (SEASON_2);

CREATE INDEX IF NOT EXISTS IX_FCT_DATE ON NBA.FCT_SHOT (GAME_DATE);