DROP TABLE IF EXISTS NBA.BRG_TEAM_PLAYER_SEASON;

CREATE TABLE NBA.BRG_TEAM_PLAYER_SEASON AS
SELECT DISTINCT
	SEASON_2 AS SEASON,
	TEAM_ID,
	PLAYER_ID
FROM
	NBA.FCT_SHOT
WHERE
	SEASON_2 IS NOT NULL
	AND TEAM_ID IS NOT NULL
	AND PLAYER_ID IS NOT NULL;

CREATE INDEX IF NOT EXISTS IX_BTP_SEASON_TEAM ON NBA.BRG_TEAM_PLAYER_SEASON (SEASON, TEAM_ID);

CREATE INDEX IF NOT EXISTS IX_BTP_PLAYER ON NBA.BRG_TEAM_PLAYER_SEASON (PLAYER_ID);